### ISSUE TITLE
Set min version requirement to NC24

### ISSUE THREAD

**Issue by rawtaz** [christianlupus-nextcloud/snowflakestheme#1]
The app works fine in NC24, I suggest changing the minimum NC version requirement from 24 to 25 and releasing a new version, so that people can install it through the regular App dashboard instead of having to do it [manually](https://help.nextcloud.com/t/snowflake-effect-for-your-nextcloud-2022-nc24-nc25/151462/14) :)

**Comment by christianlupus** [comment]
Fixed in v0.0.2
